### ISSUE TITLE
Diseñar base de datos de productos

### ISSUE THREAD

**Issue by AtilioRausch** [TheCaveDevelopments/piramide-web#13]
Diseñar base de datos de productos.

> Hitos:
- Almacenar:
- - ID
- - Nombre de producto
- - Categoría
- - Precio
- - Precio de promoción/oferta
- - Descripción corta
- - Descripción detallada
- - Enlace a video tutorial (youtube)
- - URL de imágenes de muestra

Ejemplo general:
[http://piramidesoluciones.com/#!/categoria/0/pagina/0/?filtro=](url)
Ejemplo detallado:
[http://piramidesoluciones.com/#!/producto/5/](url)

**Comment by FrGonzalez415** [comment]
Teniendo el cuenta el volumen de datos y el costo operativo y a nivel de rendimiento que nos implica mantener una BD, y a su vez, la previsión de modificaciones de dichos datos, la cual seria muy poca o nula, yo creo conveniente la no aplicacion de una BD y manejar los problemas de performance que esto implica a la hora de cargar la pagina utilizando renderizado condicional , lazy loading, etc.

**Comment by AtilioRausch** [comment]
Comparto el comentario de @FrGonzalez415. La modificación de los elementos será nula o muy aislada temporalmente y el costo de mantenimiento e implementación de la BD no corresponde con su valor agregado. Se optará por un manejo con archivos de datos y/o objetos del lenguaje.
