### ISSUE TITLE
Implementar base de datos de productos

### ISSUE THREAD

**Issue by AtilioRausch** [TheCaveDevelopments/piramide-web#16]
Implementar base de datos de productos con la información de piramidesoluciones.com.

> Hitos:
- Almacenar:
- - ID
- - Nombre de producto
- - Categoría
- - Precio
- - Precio de promoción/oferta
- - Descripción corta
- - Descripción detallada
- - Enlace a video tutorial (youtube)
- - URL de imágenes de muestra

Ejemplo general:
[http://piramidesoluciones.com/#!/categoria/0/pagina/0/?filtro=](url)
Ejemplo detallado:
[http://piramidesoluciones.com/#!/producto/5/](url)

**Comment by FrGonzalez415** [comment]
Consultar #13 y definir la viabilidad de la Tarea

**Comment by AtilioRausch** [comment]
No se optó por emplear una BD. Según #13.
