### ISSUE TITLE
Pensar sistema de cuentas de usuarios

### ISSUE THREAD

**Issue by AtilioRausch** [TheCaveDevelopments/piramide-web#17]
Pensar y debatir qué beneficio brindará el logueo en la aplicación web.

> Hitos:
- Responder:
- - ¿Qué permitirá el encontrarse logueado en la aplicación?
- - ¿Sistema de chat directo con el proveedor?
- - ¿Suscripción y novedades?
- Definir requerimientos actuales y futuros discriminándolos.

**Comment by FrGonzalez415** [comment]
Creo que para el nivel de complejidad y el alcance previsto de la pagina, tener un sistema de logueo no aportaría una funcionalidad real.

**Comment by AtilioRausch** [comment]
Comparto la opinión de @FrGonzalez415.  Un sistema de logueo no aporta valor agregado.
