### ISSUE TITLE
Estructurar proyecto

### ISSUE THREAD

**Issue by TheCaveDevelopments** [TheCaveDevelopments/piramide-web#3]
Crear directorios de estructura base.

**Comment by AtilioRausch** [comment]
Estructuré el árbol del directorio pages como:

- pages
       Home
             **components**
             **styles**
             Home.jsx
En negrita marco el patrón repetido para todas pages.

**Comment by AtilioRausch** [comment]
@FrGonzalez415 cuando puedas y cerramos esta issue.  Te encargo los barrels sobre la branch de #10 .

**Comment by FrGonzalez415** [comment]
Implementados los barrels, paso la tarea a TEST
